[font]
size = 8

  [font.normal]
  family = "FiraMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FiraMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "FiraMono Nerd Font"
  style = "Italic"

# [shell]
# program = "tmux"
